apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,SkipDryRunOnMissingResource=true
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  destination:
    namespace: gha-runner
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    repoURL: 'https://actions-runner-controller.github.io/actions-runner-controller'
    chart: actions-runner-controller
    targetRevision: '>=0.23.2'
    helm:
      values: |
        authSecret:
          create: false
          name: controller-manager
        githubWebhookServer:
          enabled: false

