apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  labels:
    app: adguard
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 3000
    http:
      address: 0.0.0.0:3000
    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53
