apiVersion: v1
kind: Service
metadata:
  name: adguard
spec:
  selector:
    app: adguard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
    - protocol: TCP
      port: 443
      targetPort: 3000
      name: https
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns
    - protocol: TCP
      port: 784
      targetPort: 784
      name: dns-over-quic1
    - protocol: TCP
      port: 853
      targetPort: 853
      name: dns-over-quic2
  type: LoadBalancer

