apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emote
  namespace: argo-cd
spec:
  destination:
    namespace: emote
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    targetRevision: HEAD
    repoURL: 'https://github.com/slashr/app-manifests.git'
    path: src/emote
