apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mediaserver
  namespace: argo-cd
spec:
  destination:
    namespace: mediaserver 
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    targetRevision: HEAD
    repoURL: 'https://github.com/slashr/app-manifests.git'
    path: src/mediaserver
