apiVersion: v1
kind: Service
metadata:
  name: adguard
spec:
  selector:
    app: adguard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 443
      name: https
    - protocol: TCP
      port: 53
      targetPort: 53
      name: https
    - protocol: TCP
      port: 784
      targetPort: 784
      name: https
    - protocol: TCP
      port: 853
      targetPort: 853
      name: https
  type: ClusterIP

