apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clearml-agent
  namespace: argo-cd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'clearml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  project: "default"
  source:
    repoURL: 'https://allegroai.github.io/clearml-helm-charts'
    chart: 'clearml-agent'
    targetRevision: '5.1.1'
    helm:
      values: |
        agentk8sglue:
          # -- Reference to Api server url
          apiServerUrlReference: "https://api.akashnair.com"
          # -- Reference to File server url
          fileServerUrlReference: "https://files.akashnair.com"
          # -- Reference to Web server url
          webServerUrlReference: "https://clearml.akashnair.com"

          queue: k8s_scheduler

