apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: homelab-map-runner
  namespace: arc-system
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true, SkipDryRunOnMissingResource=true
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  replicas: 1
  template:
    spec:
      repository: slashr/homelab-map
      labels:
        - self-hosted
        - linux
        - arm64
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - stanley
                      - phyllis

