apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argo-cd
spec:
  destination:
    namespace: signoz
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  project: default
  source:
    targetRevision: '>=0.84.0'
    repoURL: 'https://charts.signoz.io'
    chart: signoz
    helm:
      values: |
        alertmanager:
          enabled: true
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            external-dns.alpha.kubernetes.io/hostname: signoz.shrub.dev
            external-dns.alpha.kubernetes.io/target: 130.61.64.164
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: signoz.shrub.dev
              paths:
                - path: /
                  pathType: ImplementationSpecific
                  port: 8080
          tls:
            - hosts:
                - signoz.shrub.dev
              secretName: signoz-tls

