apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argo-cd
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
#    syncOptions:
#    - CreateNamespace=true
  project: default
  source:
    targetRevision: '>=5.*.*'
    repoURL: 'https://stefanprodan.github.io/podinfo'
    chart: podinfo
    helm:
      values: |
        replicaCount: '2'
        ingress:
          enabled: true
          className: "nginx"
          hosts:
            - host: 7b7f-87-10-70-185.eu.ngrok.io
              paths:
                - path: /podinfo
                  pathType: ImplementationSpecific
