apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: homelab-runner
  namespace: gha-runner 
spec:
  replicas: 1
  template:
    spec:
      repository: slashr/homelab
      labels:
        - self-hosted
        - linux
        - arm64
      # Use latest image (has pip but Python 3.8) - will use ubuntu-latest for pre-commit jobs
      image: summerwind/actions-runner:latest
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - stanley
                      - phyllis

