apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: homelab-runner
  namespace: gha-runner 
spec:
  replicas: 1
  template:
    spec:
      repository: slashr/homelab
      labels:
        - self-hosted
        - linux
        - arm64
      # Use ubuntu-22.04 runner image and install pip via dockerEnv command
      image: summerwind/actions-runner:ubuntu-22.04
      # Install pip before runner starts
      command: ["/bin/bash"]
      args:
        - -c
        - |
          apt-get update && apt-get install -y python3-pip && /entrypoint.sh
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: name
                    operator: In
                    values:
                      - stanley
                      - phyllis

